services:
  - type: web
    name: dogsTOOLomg
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd /opt/render/project/src && PYTHONPATH=/opt/render/project/src gunicorn --bind 0.0.0.0:$PORT quantum_hermetic_gematria.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production 