services:
  - type: web
    name: dogsTOOLomg
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir quantum_hermetic_gematria app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PYTHONPATH
        value: quantum_hermetic_gematria
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production 