services:
  - type: web
    name: dogsTOOLomg
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --log-level debug --timeout 120
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true" 