services:
  - type: web
    name: quantum-hermetic-gematria
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd quantum_hermetic_gematria && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: quantum_hermetic_gematria 