services:
  - type: web
    name: dogsTOOLomg
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=/opt/render/project/src gunicorn quantum_hermetic_gematria.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production 