services:
  - type: web
    name: quantum-hermetic-gematria
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn quantum_hermetic_gematria.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production 